### ISSUE TITLE
alt version incompatible

### ISSUE THREAD

**Issue by rt012** [mrblueblue/react-native-alt-demo#3]
Hey guys, 

is it possible that the current alt version isn't compatible with the current react native version? 
I only get a white screen after the integration of alt. [refer to this post](https://github.com/facebook/react-native/issues/1214)

**Comment by mrblueblue** [comment]
wow, this slipped by me....I will be updating this demo this weekend. There've been many changes in react-native and alt since I've made this demo!

**Comment by mrblueblue** [comment]
I don't believe there are any incompatibilities. I recently updated this project and with the newest versions of react-native and alt. Everything seems to be working fine.

Let me know if the problem persists!
